"""0002 shared spine

Revision ID: 0002_shared_spine
Revises: 0001_create_schemas
Create Date: 2026-06-26

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0002_shared_spine'
down_revision = '0001_create_schemas'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Prerequisites (hand-added — autogenerate does not emit extensions):
    # - citext: required by users.email. Created in public so public.citext is
    #   resolvable from the shared schema via search_path.
    # - gen_random_uuid(): built-in on PostgreSQL 13+ (RDS is PG16), so no
    #   pgcrypto extension is needed for the uuid PK server defaults.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public")

    # NOTE (decision B): append-only enforcement for audit_logs (REVOKE
    # UPDATE/DELETE) is intentionally deferred — it requires a dedicated
    # least-privilege app DB role distinct from the migration/owner role, which
    # does not exist yet (app currently connects as the master user). The table
    # shape is correct here; the grant-based immutability lands when the app role
    # is introduced.

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('entity', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='shared'
    )
    op.create_table('plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('price_inr', sa.Numeric(), nullable=True),
    sa.Column('period', sa.Text(), nullable=True),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='shared'
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('slug'),
    schema='shared'
    )
    op.create_table('business_units',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("code IN ('STAFFING', 'ACADEMY', 'CONSULTING')", name='ck_business_units_code'),
    sa.ForeignKeyConstraint(['tenant_id'], ['shared.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_business_units_tenant_code'),
    schema='shared'
    )
    op.create_table('tenant_subscriptions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('razorpay_subscription_id', sa.Text(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('trialing','active','past_due','cancelled')", name='ck_tenant_subscriptions_status'),
    sa.ForeignKeyConstraint(['plan_id'], ['shared.plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['shared.tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id'),
    schema='shared'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['shared.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email'),
    schema='shared'
    )
    op.create_table('memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_unit_id', sa.UUID(), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['shared.business_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['shared.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'business_unit_id'),
    schema='shared'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memberships', schema='shared')
    op.drop_table('users', schema='shared')
    op.drop_table('tenant_subscriptions', schema='shared')
    op.drop_table('business_units', schema='shared')
    op.drop_table('tenants', schema='shared')
    op.drop_table('plans', schema='shared')
    op.drop_table('audit_logs', schema='shared')
    # ### end Alembic commands ###
    # citext extension intentionally NOT dropped on downgrade (may be shared by
    # other objects; dropping it is destructive and rarely desired).
