"""0004 staffing core — clients / jobs / candidates / applications (Part 5)

Revision ID: 0004_staffing_core
Revises: 0003_seed_owner_tenant
Create Date: 2026-06-27

Staffing tables in the `staffing` schema. clients/jobs/applications are two-axis
(tenant_id + business_unit_id TEXT+CHECK); **candidates are TENANT-scoped** (no
business_unit_id) — a tenant-level talent pool considerable across verticals; the
vertical lives on applications.business_unit_id (see DECISIONS: candidate scoping).
Soft-delete, in-schema FKs, composite/GIN indexes, applications stage CHECK.
citext + gen_random_uuid already exist (0002); no new extension.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0004_staffing_core'
down_revision = '0003_seed_owner_tenant'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('pan', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('total_exp', sa.Numeric(), nullable=True),
    sa.Column('resume_s3_key', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('search_doc', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='staffing'
    )
    op.create_index('ix_candidates_search', 'candidates', ['search_doc'], unique=False, schema='staffing', postgresql_using='gin')
    op.create_index('ix_candidates_skills', 'candidates', ['skills'], unique=False, schema='staffing', postgresql_using='gin')
    op.create_index('ix_candidates_tenant', 'candidates', ['tenant_id'], unique=False, schema='staffing')
    op.create_table('clients',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('business_unit_id', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("business_unit_id IN ('STAFFING', 'ACADEMY', 'CONSULTING')", name='ck_clients_business_unit'),
    sa.PrimaryKeyConstraint('id'),
    schema='staffing'
    )
    op.create_index('ix_clients_tenant_bu', 'clients', ['tenant_id', 'business_unit_id'], unique=False, schema='staffing')
    op.create_table('jobs',
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('min_exp', sa.Integer(), nullable=True),
    sa.Column('max_exp', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('business_unit_id', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("business_unit_id IN ('STAFFING', 'ACADEMY', 'CONSULTING')", name='ck_jobs_business_unit'),
    sa.ForeignKeyConstraint(['client_id'], ['staffing.clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='staffing'
    )
    op.create_index('ix_jobs_client_id', 'jobs', ['client_id'], unique=False, schema='staffing')
    op.create_index('ix_jobs_tenant_bu', 'jobs', ['tenant_id', 'business_unit_id'], unique=False, schema='staffing')
    op.create_table('applications',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Text(), server_default=sa.text("'sourced'"), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('business_unit_id', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("business_unit_id IN ('STAFFING', 'ACADEMY', 'CONSULTING')", name='ck_applications_business_unit'),
    sa.CheckConstraint("stage IN ('sourced', 'screened', 'assessed', 'submitted', 'interview', 'offer', 'placed', 'rejected', 'on_hold')", name='ck_applications_stage'),
    sa.ForeignKeyConstraint(['candidate_id'], ['staffing.candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['staffing.jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'candidate_id', name='uq_applications_job_candidate'),
    schema='staffing'
    )
    op.create_index('ix_applications_candidate_id', 'applications', ['candidate_id'], unique=False, schema='staffing')
    op.create_index('ix_applications_job_id', 'applications', ['job_id'], unique=False, schema='staffing')
    op.create_index('ix_applications_tenant_bu', 'applications', ['tenant_id', 'business_unit_id'], unique=False, schema='staffing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_applications_tenant_bu', table_name='applications', schema='staffing')
    op.drop_index('ix_applications_job_id', table_name='applications', schema='staffing')
    op.drop_index('ix_applications_candidate_id', table_name='applications', schema='staffing')
    op.drop_table('applications', schema='staffing')
    op.drop_index('ix_jobs_tenant_bu', table_name='jobs', schema='staffing')
    op.drop_index('ix_jobs_client_id', table_name='jobs', schema='staffing')
    op.drop_table('jobs', schema='staffing')
    op.drop_index('ix_clients_tenant_bu', table_name='clients', schema='staffing')
    op.drop_table('clients', schema='staffing')
    op.drop_index('ix_candidates_tenant', table_name='candidates', schema='staffing')
    op.drop_index('ix_candidates_skills', table_name='candidates', schema='staffing', postgresql_using='gin')
    op.drop_index('ix_candidates_search', table_name='candidates', schema='staffing', postgresql_using='gin')
    op.drop_table('candidates', schema='staffing')
    # ### end Alembic commands ###
